### ISSUE TITLE
[Feature] Start/stop with resource manager

### ISSUE THREAD

**Issue by SaphuA** [JetBrains/teamcity-azure-plugin#37]
As management certificates are deprecated would love to be able to do starting/stopping with the resource manager plugin.

**Comment by erichexter** [comment]
👍

>

-- 
Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by gambrose** [comment]
This is a blocker for us moving from the classic Azure plugin.

**Comment by erichexter** [comment]
ping @dtretyakov

**Comment by dtretyakov** [comment]
@erichexter, we consider implementing it in the next plugin version.

Could you please share details about your use case: why you prefer `start/stop` behaviour instead of `clone`?

If it's a start time consideration we have an idea to reuse created machines in the clone behavior, so you will have a chance to create a pool of stopped/deallocated vms which are ready to start same way as in the start/stop behavior. For details see issue #34.

**Comment by gambrose** [comment]
@dtretyakov yeah, startup time is a consideration but also we already have tools/knowledge around creating Azure vms.
I would like to keep the flexibility that ARM templates give me, instead of having to rely on the plugins opinion on how a vm should be configured.
We find that disk io a limiting factor in build times so we would like the flexibly to setup the build machines to use premium storage or stripped disks.
Also we would like to keep the build agent repos between builds to we can just do an incremental update for faster builds.

**Comment by SaphuA** [comment]
@dtretyakov Yes that is exactly the reason. Creating a new VM takes magnitudes longer than starting one.

**Comment by dtretyakov** [comment]
@SaphuA, recent change in issue https://github.com/JetBrains/teamcity-azure-plugin/issues/34 brings ability to reuse created virtual machines. While terminating it just moves vm into Stopped/Deallocated state and on demand starts it again.

Please try to [download updated plugin](https://plugins.jetbrains.com/plugin/9260?pr=teamcity) from the gallery and enable `Reuse allocated virtual machines` for your images.

**Comment by chlsmith** [comment]
I'd love to see start/stop instead of a full clone.  I need my machines to have static public IP addresses, and the current cloning doesn't allow me to link an existing public IP to a machine.   Not to mention the time to get things built.

**Comment by mrahl** [comment]
For us the reason to use start/stop is that we can keep the workspace to make the checkouts faster. The Azure VPN speeds suck (we have Gbit speeds to/from Internet in general, but we've tried two different Azure regions close to us without even getting 20 Mbit/s throughput through VPN) so clean checkouts adds several minutes to build times.

We have many builds for many repos so the chance that the same workspace is reused during the lifetime of the Azure agent is very low, effectively rendering every build a clean checkout. We're considering express route but it is a very expensive solution.

We've considered agent-side checkouts and a git mirror in Azure, but it causes configuration problems since we also have build agents on-site.

**Comment by dtretyakov** [comment]
@chlsmith, @mrahl, great thanks for explanation. It's a high priority feature request.

**Comment by mrahl** [comment]
@dtretyakov thank you, but after commenting I also saw your comment about issue #34 and tried the updated plugin and it seems to solve our problem well already!

**Comment by eakukin** [comment]
@dtretyakov "Reuse allocated virtual machines" works fine if delay between stopping agent and starting it quite small 1-4 hours. In our case, they stopped in the evening, and in the morning (delay 6-8 hours, for weekends up to 48hours), plugin creating new agents instead of starting old one. This behavior is not useful, new agents has new ip addresses, without needed permission, and build failing.  Could you fix that?

**Comment by dtretyakov** [comment]
@eakukin, it looks like a bug.

Could you please report it in the [TeamCity tracker](https://youtrack.jetbrains.com/issues/TW) and securely attach [`teamcity-clouds.log` file](https://confluence.jetbrains.com/display/TCDL/TeamCity+Server+Logs#TeamCityServerLogs-GeneralLoggingDescription)?

**Comment by dtretyakov** [comment]
In the [latest snapshot plugin build](https://teamcity.jetbrains.com/viewType.html?buildTypeId=TeamcityAzurePlugin_BuildResourceManager&branch_TeamcityAzurePlugin=%3Cdefault%3E&guest=1) available "start/stop" mode. Please let me know if it completely covers your use cases.

![image](https://user-images.githubusercontent.com/1025927/34441549-b2e85d60-ecbc-11e7-9dc2-649351e6493d.png)

**Comment by dtretyakov** [comment]
This mode is available in Azure plugin 0.7.0

**Comment by gambrose** [comment]
@dtretyakov I have only just had a chance to test this but it seems to be working well. 👍 

I did notice an issue with the Name Prefix missing the first letter of the image name.
![image](https://user-images.githubusercontent.com/2676070/36449825-eae6c0b2-1683-11e8-83bb-cd70d3ce852f.png)

**Comment by dtretyakov** [comment]
@gambrose, thanks for reporting. Will fix it as apart of #89
