### ISSUE TITLE
unchecked "Reuse allocated virtual machines" does not delete VMs

### ISSUE THREAD

**Issue by btdevopsteam** [JetBrains/teamcity-azure-plugin#61]
Good day

Enhancement #36 works well and consolidate resources into a Resource Group

We notice that when "Reuse allocated virtual machines" is unchecked, the plugin simple "forgets" about it in TeamCity and does not really stop the VM nor delete it

**Comment by dtretyakov** [comment]
@btdevopsteam, thanks for reporting. I tried to fix the possible cause in the latest plugin build. Could you please try updating plugin, then go to Administration -> Diagnostics -> Troubleshooting page and enable `debug-cloud`  logging preset. Then start a new build agent and stop them. After that enable `default` logging preset and check whether VM and associated resources has been properly deleted. If you find leftovers please create a new issue in the [TeamCity issue tracker](https://youtrack.jetbrains.com/issues/TW) and securely attach in it `teamcity-clouds.log` file for investigation.

**Comment by konste** [comment]
> Could you please try updating plugin
I'm lost - where shall we download the very latest version of the plugin?

**Comment by dtretyakov** [comment]
@konste, [here it](https://teamcity.jetbrains.com/viewType.html?buildTypeId=TeamcityAzurePlugin_BuildResourceManager&branch_TeamcityAzurePlugin=%3Cdefault%3E&guest=1).

**Comment by dtretyakov** [comment]
@btdevopsteam, @konste, please let me know whether it was solved in the latest plugin builds?

**Comment by btdevopsteam** [comment]
Thank you for working on this and sorry for the non-reply

Just installed **SNAPSHOT-20170816163918** and restarted TeamCity service, the behavior is as before updating
- stop a machine
- the machine disappears from TeamCity
- checked portal.azure.com, that VM is still running
- after a while that machine reappears on the TeamCity

Is there any steps we need to take after updating the plugin?
Is there anything we can provide to assist the investigation?

**Comment by dtretyakov** [comment]
@btdevopsteam, interesting could not reproduce it on my side, so I need logs to investigate the cause.

Please follow the instructions in https://github.com/JetBrains/teamcity-azure-plugin/issues/61#issuecomment-321786042 and attach logs into new issue in TeamCity tracker.

**Comment by btdevopsteam** [comment]
Thanks @dtretyakov 

[TW-51243](https://youtrack.jetbrains.com/issue/TW-51243)

**Comment by dtretyakov** [comment]
@btdevopsteam, got it. It seems that you have missing deployments metadata for image `azbuild19-` in the group `multiple`. Could not realize who did it, so could you please open Audit log for this group and try to find `Delete Deployments` event for deployment with name `azbuild19-5`? Whether it was TeamCity app and when it happens?

When used build agents deployment into specific resource group the plugin deeply depends on metadata stored for deployment, so when it is missing TeamCity could not find list of allocated resources and remove them.

Could you please try to cleanup this group manually or remove and recreate it (if possible, since it is faster). Then try to start a new build agent in it, stop agent and it should properly remove all allocated resources.

I will try to improve logging for such cases when no metadata for deployment are available in resource group.

**Comment by btdevopsteam** [comment]
Made a new Image and retry

Logs uploaded to youtrack, let's continue the discussion on youtrack for the moment

**Comment by dtretyakov** [comment]
@btdevopsteam, oh, thanks, it should be fixed in the [snapshot build 103+](https://teamcity.jetbrains.com/viewType.html?buildTypeId=TeamcityAzurePlugin_BuildResourceManager&branch_TeamcityAzurePlugin=%3Cdefault%3E&guest=1&tab=buildTypeStatusDiv). Please let me know if it properly works.

**Comment by btdevopsteam** [comment]
Thanks!

VMs (network interfaces and OS disks) are now being deleted
