### ISSUE TITLE
Unable to choose pool / editing other settings results in image going to <Project pool>

### ISSUE THREAD

**Issue by btdevopsteam** [JetBrains/teamcity-azure-plugin#70]
We are using the latest **SNAPSHOT-20170918103035**

1/ Unable to choose pool

We noticed that sometimes, the **Agent Pool:** selection is empty, only >Project pool> is present

![image](https://user-images.githubusercontent.com/30698023/30999221-67da0ae2-a506-11e7-8742-7930ec1127e7.png)

2/ Editing other settings results in image going to <Project pool>

We also noticed that when we edit settings of the image, e.g. update **Instances Limit:**, the **Agent Pool:** changes to Default pool despite us not changing it

**Comment by dtretyakov** [comment]
@btdevopsteam, there was a bug with project pools selection. Previously it was possible to select any agent pool which [actually wouldn't work](https://confluence.jetbrains.com/display/TCDL/Agent+Cloud+Profile#AgentCloudProfile-AddingAgentImage).

For cloud images in TeamCity it is possible to use virtual project pool for current project `<Project pool>` or any project pool which has current project assignment:
![image](https://user-images.githubusercontent.com/1025927/31021621-a7c84594-a536-11e7-8537-8814835b64aa.png)

Since `Default` pool value was stored for you cloud images before fix of this bug it could in some cases reset to Default.

Could you please try to assign in Default pool this project with cloud profile and than change agent pool for cloud profile images to `<Project pool>`. After that you could remove this project assignment from Default pool.

**Comment by btdevopsteam** [comment]
Thanks!

We happen to be using new images and the issue appears to be absent in the new images :-)
