### ISSUE TITLE
Agent upgrades each time it starts up from Image

### ISSUE THREAD

**Issue by mscrivo** [JetBrains/teamcity-azure-plugin#81]
We've been having this issue for a while, where agents created from images go through the upgrade step everytime they are started up.  Even if I let an agent fully upgrade, then take a new image, and use that image, the next time it starts up, it will upgrade again.  This in addition to the time it takes Azure to start a VM is killing us. 

We're using TC 2017.2 (50574) and 0.65 of the plugin.  We have the plugin set to re-use VM's as well.

I've attached a sample upgrade.log from one of the agents.
  
[upgrade.log](https://github.com/JetBrains/teamcity-azure-plugin/files/1531520/upgrade.log)

**Comment by dtretyakov** [comment]
@mscrivo, thanks for reporting. Could you please also share the `teamcity-agent.log` file from this agent, since `upgrade.log` contains no details about the cause of this upgrade. You could file an issue in the [TeamCity tracker](https://github.com/JetBrains/teamcity-azure-plugin#feedback), where it's possible to attach logs privately.

**Comment by mscrivo** [comment]
done: https://youtrack.jetbrains.com/issue/TW-52842
